name: web

on:
  push:
    paths: 
      - 'Modul_8'

  workflow_dispatch:
    inputs:
      action_type:
        description: 'What action should be performed? (apply / destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

jobs:
  resourcegroups:
    runs-on: ubuntu-latest

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      # WORKING_DIR: ../../../Modul_8

    steps:
      - uses: actions/checkout@v4

      - name: 'Terraform init'
        id: init
        run: terraform init
        # working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan -var=ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
        # working-directory: ${{ env.WORKING_DIR }}
      
      # - name: 'Terraform apply'
      #   id: apply
      #   run: terraform apply -var=ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} -auto-approve
      #   # working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform apply'
        if: github.event.inputs.action_type == 'apply'
        id: apply
        run: terraform apply -var=ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} -auto-approve

      - name: 'Terraform destroy'
        if: github.event.inputs.action_type == 'destroy'
        id: destroy
        run: terraform destroy -auto-approve
          
